//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo1
    {
        public int idArchivo { get; set; }
        public string nombreArchivo { get; set; }
        public string tipoContenido { get; set; }
        public byte[] contenidoArchivo { get; set; }
        public int idProyecto { get; set; }
        public string documentos { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
