//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class prueba1Entities : DbContext
    {
        public prueba1Entities()
            : base("name=prueba1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo1> Archivo1 { get; set; }
        public virtual DbSet<Archivo2> Archivo2 { get; set; }
        public virtual DbSet<Archivo3> Archivo3 { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<CatalogoEntregable> CatalogoEntregable { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
    
        public virtual ObjectResult<selectComentarios_Result> selectComentarios(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectComentarios_Result>("selectComentarios", idProyectoParameter);
        }
    
        public virtual ObjectResult<string> selectCurso(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("selectCurso", idProyectoParameter);
        }
    
        public virtual ObjectResult<selectCursoTodo_Result> selectCursoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectCursoTodo_Result>("selectCursoTodo");
        }
    
        public virtual ObjectResult<selectEmpresaTodo_Result> selectEmpresaTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectEmpresaTodo_Result>("selectEmpresaTodo");
        }
    
        public virtual ObjectResult<string> selectEstudiante(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("selectEstudiante", idProfesorParameter);
        }
    
        public virtual ObjectResult<selectGrupo_Result> selectGrupo(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectGrupo_Result>("selectGrupo", idProyectoParameter);
        }
    
        public virtual ObjectResult<selectGrupo1_Result> selectGrupo1(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectGrupo1_Result>("selectGrupo1", idProfesorParameter);
        }
    
        public virtual ObjectResult<selectProfesor_Result> selectProfesor(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProfesor_Result>("selectProfesor", idProyectoParameter);
        }
    
        public virtual ObjectResult<selectProfesor1_Result> selectProfesor1(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProfesor1_Result>("selectProfesor1", idProfesorParameter);
        }
    
        public virtual ObjectResult<selectProfesorTodo_Result> selectProfesorTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProfesorTodo_Result>("selectProfesorTodo");
        }
    
        public virtual ObjectResult<selectProyecto_Result> selectProyecto(Nullable<int> idProyecto)
        {
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProyecto_Result>("selectProyecto", idProyectoParameter);
        }
    
        public virtual ObjectResult<selectProyecto1_Result> selectProyecto1(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProyecto1_Result>("selectProyecto1", idProfesorParameter);
        }
    
        public virtual ObjectResult<selectProyectoTodo_Result> selectProyectoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProyectoTodo_Result>("selectProyectoTodo");
        }
    }
}
